StudentApplicationSystem/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentApplicationSystem.Models;

namespace StudentApplicationSystem.Controllers
{
    public class QuestionController : Controller
    {
        private StudentApplicationSystemEntities db = new StudentApplicationSystemEntities();

        // GET: Question
        public ActionResult Index()
        {
            if(CheckVisitor())
            {
                // If non-user wants to reach question poll.
                return RedirectToAction("NotAuthorized", "Home");
            }
            else if(!CheckAdmin())
            {
                // If normal user wants to reach question poll.
                return RedirectToAction("NotAuthorized", "Home");
            }            
            return View(db.Questions.ToList());
        }

        // GET: Question/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (CheckVisitor())
            {
                // If non-user wants to reach question details.
                return RedirectToAction("NotAuthorized", "Home");
            }
            else if (!CheckAdmin())
            {
                // If normal user wants to reach question details.
                return RedirectToAction("NotAuthorized", "Home");
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Question/Create
        public ActionResult Create()
        {
            if (CheckVisitor())
            {
                // If non-user wants to reach question create.
                return RedirectToAction("NotAuthorized", "Home");
            }
            else if (!CheckAdmin())
            {
                // If normal user wants to reach question create.
                return RedirectToAction("NotAuthorized", "Home");
            }
            JobController jc = new JobController();
            List<SelectListItem> items = jc.CategoryList();
            ViewBag.Categories = items;
            return View();
        }

        // POST: Question/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "category, question1")] Question question)
        {
            if (ModelState.IsValid)
            {
                question.cd_creater = (int)Session["userId"];
                question.dt_created = DateTime.Now;
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(question);
        }

        // GET: Question/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (CheckVisitor())
            {
                // If non-user wants to reach question edit.
                return RedirectToAction("NotAuthorized", "Home");
            }
            else if (!CheckAdmin())
            {
                // If normal user wants to reach question edit.
                return RedirectToAction("NotAuthorized", "Home");
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            JobController jc = new JobController();
            List<SelectListItem> items = jc.CategoryList();
            ViewBag.Categories = items;
            return View(question);
        }

        // POST: Question/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "questionId,question1,cd_creater,dt_created,category")] Question question)
        {
            if (ModelState.IsValid)
            {
                question.cd_modifier = (int)Session["userId"];
                question.dt_modified = DateTime.Now;
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // GET: Question/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (CheckVisitor())
            {
                // If non-user wants to reach question edit.
                return RedirectToAction("NotAuthorized", "Home");
            }
            else if (!CheckAdmin())
            {
                // If normal user wants to reach question edit.
                return RedirectToAction("NotAuthorized", "Home");
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Question/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public bool CheckVisitor()
        {
            //If visitor return true, if user return false.
            return Session["userName"] == null ? true : false;
        }

        public bool CheckAdmin()
        {
            // If admin return true else false.
            return (int)Session["isAdmin"] == 1 ? true : false;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentApplicationSystem/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentApplicationSystem.Models;

namespace StudentApplicationSystem.Controllers
{
    public class UserController : Controller
    {
        private StudentApplicationSystemEntities db = new StudentApplicationSystemEntities();

        // GET: User
        public ActionResult Index()
        {
            if(CheckVisitor())
            {
                // If a visitor wants to see UserList.
                return RedirectToAction("NotAuthorized", "Home"); ;
            }
            else if(!CheckAdmin())
            {
                // If non-admin user wants to see UserList.
                return RedirectToAction("NotAuthorized", "Home"); ;
            }

            return View(db.Users.ToList());
        }

        // GET: User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                // If id parameter sent wrong.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (CheckVisitor())
            {
                // If the user is not logged in.
                return RedirectToAction("NotAuthorized", "Home");
            }
            else if (!CheckAdmin() && id != (int)Session["userId"])
            {
                // If user wants to see somebody elses' details.
                return RedirectToAction("NotAuthorized", "Home");

            }
            else
            {
                // If user is admin or non-admin user wants to see his/her own details.
                User user = db.Users.Find(id);
                if (user == null)
                {
                    // If there is no user with given ID.
                    return HttpNotFound();
                }
                return View(user);
            }
        }

        // GET: User/Create
        public ActionResult Create()
        {
            if (Session["userName"] != null)
            {
                // If logged in user wants to create another user.
                if ((int)Session["isAdmin"] == 0)
                {
                    // If this user is not admin.
                    return RedirectToAction("NotAuthorized", "Home");

                }
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    // Check for email is already in use or not.
                    bool alreadyexists = false;

                    // Iterate in Database
                    foreach (User u in db.Users.ToList())
                    {
                        if (u.email.Equals(user.email))
                        {
                            // If already in use break the loop and change match data.
                            alreadyexists = true;
                            break;
                        }
                    }

                    if (alreadyexists)
                    {
                        // In case of duplicate emails, produce an error message and return back to register page.
                        ModelState.AddModelError(string.Empty, "This email already in use.");
                        return View();
                    }

                    if (Session["userName"] == null)
                    {
                        // If create accesed by register.
                        user.BoolValue = false;
                    }

                    // Creating time log stored.
                    user.dt_created = DateTime.Now;
                    db.Users.Add(user);
                    db.SaveChanges();
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }
                    throw;
                }
                return RedirectToAction("Index", "Home", null);
            }

            return View(user);
        }




        // GET: User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                // Checks ID parameter passed right.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (CheckVisitor())
            {
                // If non user person wants to reach Edit page.
                return RedirectToAction("NotAuthorized", "Home");
            }
            else
            {
                if (!CheckAdmin() && (int)Session["userId"] != id)
                {
                    // If user is not an admin and not editing (her/him)self.
                    return RedirectToAction("NotAuthorized", "Home");
                }
            }

            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        
        // POST: User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                // Check for email is already in use or not.
                bool alreadyexists = false;

                // Iterate in Database
                foreach (User u in db.Users.ToList())
                {
                    if (u.email.Equals(user.email) && !(user.userId.Equals(u.userId)))
                    {                        // If already in use break the loop and change match data.
                        alreadyexists = true;
                        break;
                    }
                }

                if (alreadyexists)
                {
                    // In case of duplicate emails, produce an error message and return back to register page.
                    ModelState.AddModelError(string.Empty, "This email already in use.");
                    return RedirectToAction("Edit", new { id = user.userId });
                }

                if ((int)Session["isAdmin"] != 1)
                    user.BoolValue = false;
                user.cd_modifier = (int)Session["userId"];
                user.dt_modified = DateTime.Now;
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                if((int)Session["isAdmin"] != 1)
                {
                    return RedirectToAction("Details", new { id = user.userId });
                }
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                // Checks ID parameter passed right.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if(CheckVisitor())
            {
                // If non-user person wants to reach delete action.
                return RedirectToAction("NotAuthorized", "Home");
            }
            else
            {
                // If there is logged in user.
                if (!CheckAdmin())
                {
                    // If the user is not admin.
                    return RedirectToAction("NotAuthorized", "Home");
                }
            }
            
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public bool CheckVisitor()
        {
            //If visitor return true, if user return false.
            return Session["userName"] == null ? true : false;
        }

        public bool CheckAdmin()
        {
            // If admin return true else false.
            return (int)Session["isAdmin"] == 1 ? true : false;
        }

    }
}

StudentApplicationSystem/Views/Question/Create.cshtml
@model StudentApplicationSystem.Models.Question

@{
    ViewBag.Title = "Create Question";
}

<h2>Add New Question</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.question1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.question1, new { rows = 10, columns = 40, htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.question1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.category, (IEnumerable<SelectListItem>)ViewBag.Categories, "-- Select Category --", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <p>
                <button class="btn btn-success" type="submit">
                    <span class="glyphicon glyphicon-plus"></span> Add Question
                </button>
            </p>
        </div>
    </div>
</div>
}

<div>
    <button class="btn btn-link" onclick="location.href='@Url.Action("Index", "Question")';return false;">
        <span class="glyphicon glyphicon-arrow-left"></span> Back To List
    </button>
</div>

StudentApplicationSystem/Views/Question/Delete.cshtml
@model StudentApplicationSystem.Models.Question

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this question?</h3>
<div>
    <hr class="soft"/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.question1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cd_creater)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cd_creater)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cd_modifier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cd_modifier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_modified)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StudentApplicationSystem/Views/Question/Details.cshtml
@model StudentApplicationSystem.Models.Question

@{
    ViewBag.Title = "Details";
}


<h2>Question Information</h2>

<div>
    <hr class="soft"/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category1.categoryName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.question1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cd_creater)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cd_creater)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cd_modifier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cd_modifier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_modified)
        </dd>

    </dl>
</div>
<p>
    <button class="btn btn-link" onclick="location.href='@Url.Action("Edit", "Question", new { id = Model.questionId })';return false;">
        <span class="glyphicon glyphicon-search"></span> Edit
    </button>

    <button class="btn btn-link" onclick="location.href='@Url.Action("Index", "Question")';return false;">
        <span class="glyphicon glyphicon-arrow-left"></span> Back To List
    </button>
</p>

StudentApplicationSystem/Views/Question/Edit.cshtml
@model StudentApplicationSystem.Models.Question

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Question</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr class="soft" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.questionId)
    @Html.HiddenFor(model => model.dt_created)
    @Html.HiddenFor(model => model.cd_creater)

    <div class="form-group">
        @Html.LabelFor(model => model.question1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.TextAreaFor(model => model.question1, new { rows = 10, columns = 40, htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.question1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.category, (IEnumerable<SelectListItem>)ViewBag.Categories, "-- Select Category --", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <p>
                <button class="btn btn-success" type="submit">
                    <span class="glyphicon glyphicon-floppy-saved"></span> Save
                </button>
            </p>
        </div>
    </div>
</div>
}

<div>
    <button class="btn btn-link" onclick="location.href='@Url.Action("Index", "Question")';return false;">
        <span class="glyphicon glyphicon-arrow-left"></span> Back To List
    </button>
</div>

StudentApplicationSystem/Views/Question/Index.cshtml
@model IEnumerable<StudentApplicationSystem.Models.Question>

@{
    /**/

    ViewBag.Title = "Index";
}

@Styles.Render("~/Content/filtergrid.css")
@Scripts.Render("~/Scripts/tablefilter_all_min.js")

<h2>Questions</h2>
<div>
    <p>
        <button class="btn btn-success" onclick="location.href='@Url.Action("Create", "Question")';return false;">
            <span class="glyphicon glyphicon-plus"></span> Add Question
        </button>
    </p>
</div>
<hr class="soft" />

<div class="container table-responsive">

    @if (Model.Count() == 0)
    {
        <text>There is no question!</text>
    }
    else
    {
        <table class="table table-striped" id="myTable">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.question1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.cd_creater)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.cd_modifier)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.dt_created)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.dt_modified)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category1.categoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.question1)
                </td>
                <td>
                    <a href=@Url.Action("Details", "User", new { id = item.cd_creater })><i class="glyphicon glyphicon-zoom-in"> @item.cd_creater </i></a>
                </td>
                <td>
                    @if (item.cd_modifier != null)
                    {
                        <a href=@Url.Action("Details", "User", new { id = item.cd_modifier })><i class="glyphicon glyphicon-zoom-in"> @item.cd_modifier </i></a>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.cd_modifier)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dt_created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dt_modified)
                </td>
                <td>
                    <a href=@Url.Action("Edit", new { id = item.questionId })><i class="glyphicon glyphicon-edit"> Edit </i></a>
                    <a href=@Url.Action("Details", new { id = item.questionId })><i class="glyphicon glyphicon-zoom-in"> Details </i></a>
                    <a href=@Url.Action("Delete", new { id = item.questionId })><i class="glyphicon glyphicon-remove"> Delete </i></a>
                </td>
            </tr>
            }

        </table>


        <script>
            var table2_Props = {
                paging: true,
                paging_length: 5,
                rows_counter: true,
                rows_counter_text: "Questions:",
                btn_reset: true,
                loader: true,
                loader_text: "Loading...",
                col_0: "select",
                col_2: "select",
                col_3: "select",
                col_6: "none",
                display_all_text: " [ Show all ] ",
                sort_select: true
            };
            var tf2 = setFilterGrid("myTable", table2_Props);

        </script>
    }
</div>