StudentApplicationSystem/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentApplicationSystem.Models;

namespace StudentApplicationSystem.Controllers
{
    public class JobController : Controller
    {
        private StudentApplicationSystemEntities db = new StudentApplicationSystemEntities();

        // GET: Job
        public ActionResult Index()
        {
            if(CheckVisitor())
            {
                // No visitor access.
                return RedirectToAction("NotAuthorized", "Home");
            }
            return View(db.Jobs.ToList());
        }

        // GET: Job/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (CheckVisitor())
            {
                // No visitor access.
                return RedirectToAction("NotAuthorized", "Home");
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Job/Create
        public ActionResult Create()
        {
            if (CheckVisitor())
            {
                // No visitor access.
                return RedirectToAction("NotAuthorized", "Home");
            }
            if (!CheckAdmin())
            {
                return RedirectToAction("NotAuthorized", "Home");
            }
            List<SelectListItem> items = CategoryList();
            ViewBag.Categories = items;
            return View();
        }

        // POST: Job/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "jobId,applicantList,jobName,applicationStart,applicationFinish,SelectedCategories,questionNumber")] Job job)
        {
            if (ModelState.IsValid)
            {
                job.categories = string.Join(",", job.SelectedCategories);
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(job);
        }

        // GET: Job/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (CheckVisitor())
            {
                // No visitor access.
                return RedirectToAction("NotAuthorized", "Home");
            }
            if (!CheckAdmin())
            {
                return RedirectToAction("NotAuthorized", "Home");
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Job/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "jobId,applicantList,jobName,applicationStart,applicationFinish,questionNumber")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(job);
        }

        // GET: Job/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (CheckVisitor())
            {
                // No visitor access.
                return RedirectToAction("NotAuthorized", "Home");
            }
            if (!CheckAdmin())
            {
                return RedirectToAction("NotAuthorized", "Home");
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Job/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            var applications = db.Applications.Where(a => a.jobId == (job.jobId)).ToList();

            foreach (var app in applications)
            {
                Review review = db.Reviews.Where(a => a.applicationId == (app.applicationId)).FirstOrDefault();
                if(review != null)
                {
                    db.Reviews.Remove(review);
                }
                

                InterviewQuestionPaper paper = db.InterviewQuestionPapers.Find(app.paperId);

                if(paper != null)
                {
                    app.paperId = null;
                    paper.applicationId = null;
                
                    db.SaveChanges();
                    db.InterviewQuestionPapers.Remove(paper);
                    db.Applications.Remove(app);
                }
                else
                {
                    db.SaveChanges();
                    db.Applications.Remove(app);
                }


            }


            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Apply(int? id)
        {
            Session["jobId"] = id;
            return RedirectToAction("Create", "Applications");
        }


        public List<SelectListItem> CategoryList()
        {
            List<SelectListItem> selectlist = new List<SelectListItem>();
            List<Category> DList = new List<Category>();

            foreach(var category in db.Categories.ToList())
            {
                DList.Add(category);
            }
            

            foreach (var category in DList)
            {
                selectlist.Add(new SelectListItem
                {
                    Text = category.categoryName,
                    Value = category.categoryId.ToString()
                });
            }

            return selectlist;

        }

        public bool CheckVisitor()
        {
            //If visitor return true, if user return false.
            return Session["userName"] == null ? true : false;
        }

        public bool CheckAdmin()
        {
            // If admin return true else false.
            return (int)Session["isAdmin"] == 1 ? true : false;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentApplicationSystem/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentApplicationSystem.Models;

namespace StudentApplicationSystem.Controllers
{
    public class NewsController : Controller
    {
        private StudentApplicationSystemEntities db = new StudentApplicationSystemEntities();

        // GET: News
        public ActionResult Index()
        {
            return View(db.News.ToList());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        // GET: News/Create
        public ActionResult Create()
        {
            if (Session["userName"] == null)
            {
                // If non user person wants to reach Edit page.
                return RedirectToAction("NotAuthorized", "Home");
            }
            if ((int)Session["isAdmin"] == 0)
            {
                return RedirectToAction("NotAuthorized", "Home");
            }
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "newId,header,text,imageFile,BoolValue,featuredList,dt_created,dt_modified,cd_creater,cd_modifier")] New @new)
        {
            if (Session["userName"] == null)
            {
                // If non user person wants to reach Edit page.
                return RedirectToAction("NotAuthorized", "Home");
            }
            if ((int)Session["isAdmin"] == 0)
            {
                return RedirectToAction("NotAuthorized", "Home");
            }
            if (ModelState.IsValid)
            {
                if (@new.imageFile != null && @new.imageFile.ContentLength > 0)
                {
                    string FileExtension = Path.GetExtension(@new.imageFile.FileName).ToUpper();

                    if (FileExtension == ".JPG" || FileExtension == ".PNG" || FileExtension == ".JPEG")
                    {
                        byte[] bytes;
                        using (BinaryReader br = new BinaryReader(@new.imageFile.InputStream))
                        {
                            bytes = br.ReadBytes(@new.imageFile.ContentLength);
                        }

                        @new.image = bytes;
                    }
                }

                @new.dt_created = DateTime.Now;
                @new.cd_creater = (int)Session["userId"];
                db.News.Add(@new);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@new);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (Session["userName"] == null)
            {
                // If non user person wants to reach Edit page.
                return RedirectToAction("NotAuthorized", "Home");
            }
            if ((int)Session["isAdmin"] == 0)
            {
                return RedirectToAction("NotAuthorized", "Home");
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "newId,header,text,image,BoolValue,featuredList,dt_created,dt_modified,cd_creater,cd_modifier")] New @new)
        {
            if (Session["userName"] == null)
            {
                // If non user person wants to reach Edit page.
                return RedirectToAction("NotAuthorized", "Home");
            }
            if ((int)Session["isAdmin"] == 0)
            {
                return RedirectToAction("NotAuthorized", "Home");
            }
            if (ModelState.IsValid)
            {
                @new.dt_modified = DateTime.Now;
                @new.cd_modifier = (int)Session["userId"];
                db.Entry(@new).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@new);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (Session["userName"] == null)
            {
                // If non user person wants to reach Edit page.
                return RedirectToAction("NotAuthorized", "Home");
            }
            if ((int)Session["isAdmin"] == 0)
            {
                return RedirectToAction("NotAuthorized", "Home");
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["userName"] == null)
            {
                // If non user person wants to reach Edit page.
                return RedirectToAction("NotAuthorized", "Home");
            }
            if ((int)Session["isAdmin"] == 0)
            {
                return RedirectToAction("NotAuthorized", "Home");
            }
            New @new = db.News.Find(id);
            db.News.Remove(@new);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentApplicationSystem/Views/Shared/_HeaderNavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div>
                <a href=@Url.Action("Index", "Home")>
                    <img src="~/icons/navbarlogo.png" id="navbar-logo" />
                </a>
            </div>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>

                @if (Session["UserName"] != null)
                {
                    if ((int)Session["isAdmin"] == 0)
                    {
                        <!--IF USER-->
                        <li>@Html.ActionLink("Jobs", "Index", "Job")</li>
                        <li>@Html.ActionLink("Applications", "Index", "Applications")</li>
                        <li>@Html.ActionLink("Announcements", "Index", "News")</li>
                    }
                }

            </ul>
            <ul class="nav navbar-nav navbar-right">
                @if (Session["UserName"] != null)
                {
                    <li>@Html.ActionLink(Session["UserName"].ToString(), "Details", "User", new { id = Session["userId"] }, null)</li>
                    <li>@Html.ActionLink("Logout", "Logout", "User")</li>

                }
                else
                {
                    <li><a href=@Url.Action("Create", "User")><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="@Url.Action("Login", "Home")"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                }
            </ul>
        </div>
    </div>
</div>

StudentApplicationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Student Application System</title>
    <link rel="icon" href="~/logo.png">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_LeftMenu")
<div id="page-container" class="container">



    @Html.Partial("_HeaderNavBar")


    <div class="row row-offcanvas row-offcanvas-right">

        <div id="content-wrap" class="container body-content col-12 col-md-9">

            @RenderBody()

        </div>



        <footer class="noselect" id="footer">Copyright &copy; 2019<br> Ford Otosan Student Application System - Designed by Ali Baran Tasdemir</footer>
        


    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</div>
</body>
</html>

StudentApplicationSystem/Views/Shared/_LeftMenu.cshtml
@if(Session["userName"] != null && (int)Session["isAdmin"] == 1)
{      
<div id="mySidebar" class="sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

    <h3 style="color:#183068">Admin Panel</h3>

    @Html.ActionLink("Profile", "Details", "User", new { id = Session["userId"] }, null)

    <button class="dropdown-btn">
        Users
        <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-container">
        @Html.ActionLink("User List", "Index", "User")
        @Html.ActionLink("Create New User", "Create", "User")
    </div>

    <button class="dropdown-btn">
        Questions
        <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-container">
        @Html.ActionLink("Question List", "Index", "Question")
        @Html.ActionLink("Add Question", "Create", "Question")
    </div>

    <button class="dropdown-btn">
        Jobs
        <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-container">
        @Html.ActionLink("Job List", "Index", "Job")
        @Html.ActionLink("Add New Job Poster", "Create", "Job")
    </div>

    @Html.ActionLink("Applications", "Index", "Applications")

    <button class="dropdown-btn">
        Announcements
        <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-container">
        @Html.ActionLink("News List", "Index", "News")
        @Html.ActionLink("Add New", "Create", "News")
    </div>

    <button class="dropdown-btn">
        Question Categories
        <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-container">
        @Html.ActionLink("Categories List", "Index", "Categories")
        @Html.ActionLink("Add Category", "Create", "Categories")
    </div>

</div>

<script>
    var dropdown = document.getElementsByClassName("dropdown-btn");
    var i;
    
    for (i = 0; i < dropdown.length; i++) {
        dropdown[i].addEventListener("click", function () {
          this.classList.toggle("active");
          var dropdownContent = this.nextElementSibling;
          if (dropdownContent.style.display === "block") {
              dropdownContent.style.display = "none";
        } else {
            dropdownContent.style.display = "block";
        }
        });
    }

    function openNav() {
        document.getElementById("mySidebar").style.width = "250px";
        document.getElementById("main").style.marginLeft = "250px";
    }

    /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
    function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
        document.getElementById("main").style.marginLeft = "0";
    }
</script>

<div id="main">
    <button class="openbtn" onclick="openNav()">&#9776; Toggle Admin Panel</button>
</div>
}