StudentApplicationSystem/Models/Application.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApplicationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Reviews = new HashSet<Review>();
            this.InterviewQuestionPapers = new HashSet<InterviewQuestionPaper>();
        }

        [Key]
        public int applicationId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> jobId { get; set; }
        [DisplayName("CV")]
        public byte[] cv { get; set; }
        public Nullable<int> paperId { get; set; }
        [DisplayName("Created")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dt_created { get; set; }
        public string status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterviewQuestionPaper> InterviewQuestionPapers { get; set; }
        public virtual Job Job { get; set; }
        public virtual InterviewQuestionPaper InterviewQuestionPaper { get; set; }
        public virtual User User { get; set; }
        public HttpPostedFileBase cvFile { get; set; }
    }
}

StudentApplicationSystem/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.IO;
using System.Web;
using System.Web.Mvc;
using StudentApplicationSystem.Models;
using System.Configuration;
using System.Net.Http;
using System.Net.Http.Headers;

namespace StudentApplicationSystem.Controllers
{
    public class ApplicationsController : Controller
    {
        
        private StudentApplicationSystemEntities db = new StudentApplicationSystemEntities();
        private int jobId;

        // GET: Applications
        public ActionResult Index()
        {
            if (CheckVisitor())
            {
                // If non user person wants to reach Edit page.
                return RedirectToAction("NotAuthorized", "Home");
            }

            int userid = (int)Session["userId"];
            
            var user = db.Users.Where(a => a.userId.Equals(userid)).FirstOrDefault();
            if(user.isAdmin == 1)
            {
                return View(db.Applications.ToList());
            }
            var applications = user.Applications;
            
            return View(applications);
        }

        // GET: Applications/Details/5
        public ActionResult Details(int? id)
        {
            // Check if id passed right.
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (CheckVisitor())
            {
                // If non user person wants to reach Edit page.
                return RedirectToAction("NotAuthorized", "Home");
            }
            int userid = (int)Session["userId"];
            User user = db.Users.Where(a => a.userId.Equals(userid)).FirstOrDefault();
            Application application = db.Applications.Find(id);

            if (application == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Check if user is admin or has right to see the application.
            return user.isAdmin == 1 || user.Applications.Contains(application)
                ? View(application)
                : (ActionResult)new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: Applications/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "applicationId,cvFile,paperId")] Application application)
        {
            
            if (ModelState.IsValid)
            {
                if (application.cvFile != null && application.cvFile.ContentLength > 0)
                {
                    string FileExtension = Path.GetExtension(application.cvFile.FileName).ToUpper();

                    if (FileExtension == ".PDF")
                    {
                        byte[] bytes;
                        using (BinaryReader br = new BinaryReader(application.cvFile.InputStream))
                        {
                            bytes = br.ReadBytes(application.cvFile.ContentLength);
                        }
                        
                        application.cv = bytes;
                    }
                }
                application.userId = (int)Session["userId"];
                application.status = "Interview";
                User user = db.Users.Where(a => a.userId == (application.userId)).FirstOrDefault();
                application.dt_created = DateTime.Now;
                user.Applications.Add(application);

                application.jobId = (int)Session["jobId"];

                Job job = db.Jobs.Find(application.jobId);
                InterviewQuestionPaper paper = new InterviewQuestionPaper();


                int totalQuestions = (int)job.questionNumber;
                string[] categoriesArray = job.categories.Split(',');
                //var questionIds = db.Questions.OrderBy(h => Guid.NewGuid()).Select(c => c.questionId).Take(3).ToList();
                int[] numbers = new int[categoriesArray.Length];
                List<int> allquestions = new List<int>();

                for (int i = 0; i < totalQuestions; i++)
                {
                    numbers[i % (categoriesArray.Length)]++;
                }

                for(int i = 0; i < categoriesArray.Length; i++)
                {
                    int question = int.Parse(categoriesArray[i]);
                    var list = db.Questions.Where(a => a.category == question);
                    var questionIds = list.OrderBy(h => Guid.NewGuid()).Select(c => c.questionId).Take(numbers[i]).ToList();
                    allquestions.AddRange(questionIds);
                }

                paper.questionList = string.Join(",", allquestions);

                
                paper.userId = application.userId;
                paper.jobId = application.jobId;
                paper.dt_created = DateTime.Now;
                paper.cd_creater = application.userId;
                
                db.InterviewQuestionPapers.Add(paper);
                db.SaveChanges();

                application.paperId = paper.paperId;
                paper.applicationId = application.applicationId;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.userId = new SelectList(db.Users, "userId", "name", application.userId);
            return View(application);
        }

        [HttpGet]
        public FileResult Download(int? id)
        {
            Application application = db.Applications.Find(id);
            return File(application.cv, ".pdf");

        }
        
        // GET: Applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (CheckVisitor())
            {
                // If non user person wants to reach Edit page.
                return RedirectToAction("NotAuthorized", "Home");
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Application application = db.Applications.Find(id);
            int? paperId = application.paperId;
            int? reviewId = application.Reviews.First().reviewId;
            if(reviewId != null)
            {
                Review review = db.Reviews.Find(reviewId);
                review.jobId = null;
                review.applicationId = null;
                review.paperId = null;
                db.Reviews.Remove(review);
            }
            InterviewQuestionPaper interview = db.InterviewQuestionPapers.Find(paperId);
            interview.applicationId = null;
            db.SaveChanges();
            db.InterviewQuestionPapers.Remove(interview);
            db.Applications.Remove(application);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Review(int? id)
        {
            Review review = new Review
            {
                dt_created = DateTime.Now,
                applicationId = id,
                cd_creater = (int)Session["userId"]
            };

            Application application = db.Applications.Find(review.applicationId);
            review.userId = application.userId;
            review.paperId = application.paperId;
            review.jobId = application.jobId;

            db.Reviews.Add(review);
            db.SaveChanges();

            return RedirectToAction("Edit", "Reviews", new { id = review.reviewId });
        }

        public int getJobId(int jobId)
        {
            this.jobId = jobId;
            return 1;
        }

        public bool CheckVisitor()
        {
            //If visitor return true, if user return false.
            return Session["userName"] == null ? true : false;
        }
        public bool CheckAdmin()
        {
            // If admin return true else false.
            return (int)Session["isAdmin"] == 1 ? true : false;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentApplicationSystem/Views/Applications/Create.cshtml
@model StudentApplicationSystem.Models.Application

@{
    ViewBag.Title = "Create";
}

@if (Session["userName"] == null)
{
    Response.Redirect("~/Home/NotAuthorized");
}
else if ((int)Session["isAdmin"] == 0)
{
    <h2>Apply</h2>

    using (Html.BeginForm("Create", "Applications", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Application</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.cv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="cvFile" id="cvFile" multiple="multiple" /><br><br>
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

}
else
{
    Response.Redirect("~/Home/NotAuthorized");
}

StudentApplicationSystem/Views/Applications/Delete.cshtml
@model StudentApplicationSystem.Models.Application

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Application for @Model.Job.jobName</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.printName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cv)
        </dt>

        <dd>
            @if (Model.cv != null)
            {
                <p>Uploaded!</p>
            }
            else
            {
                <p>Not uploaded!</p>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paperId)
        </dt>

        <dd>
            @if (Model.paperId != null)
            {
                <a href=@Url.Action("Edit", "InterviewQuestionPapers", new { id = Model.paperId })><i class="glyphicon glyphicon-zoom-in"> Go to Interview </i></a>
            }
            else
            {
                @Html.DisplayFor(model => model.paperId)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_created)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />

            <button class="btn btn-link" onclick="location.href='@Url.Action("Index", "Applications")';return false;">
                <span class="glyphicon glyphicon-arrow-left"></span> Back To List
            </button>
        </div>
    }
</div>

StudentApplicationSystem/Views/Applications/Details.cshtml
@model StudentApplicationSystem.Models.Application

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Application</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cv)
        </dt>

        <dd>
            @if (Model.cv != null)
            {
                <p>Uploaded!</p>
            }
            else
            {
                <p>Not uploaded!</p>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paperId)
        </dt>

        <dd>
            @if (Model.paperId != null)
            {
                <a href=@Url.Action("Edit", "InterviewQuestionPapers", new { id = Model.paperId })><i class="glyphicon glyphicon-zoom-in"> Go to Interview </i></a>
            }
            else
            {
                @Html.DisplayFor(model => model.paperId)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.name)
        </dd>

    </dl>
</div>

<p>
    <button class="btn btn-link" onclick="location.href='@Url.Action("Index", "Applications")';return false;">
        <span class="glyphicon glyphicon-arrow-left"></span> Back To List
    </button>
</p>

StudentApplicationSystem/Views/Applications/Index.cshtml
@model IEnumerable<StudentApplicationSystem.Models.Application>

@{
    ViewBag.Title = "Index";
}


@Styles.Render("~/Content/filtergrid.css")
@Scripts.Render("~/Scripts/tablefilter_all_min.js")

<h2>Applications</h2>

<hr class="soft" />

<div class="container table-responsive">

    <table class="table table-striped" id="myTable">
        <thead>
            <tr>
                @if ((int)Session["isAdmin"] == 1)
                {
                    <th>
                        @Html.DisplayNameFor(model => model.User.userId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.User.name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.User.email)
                    </th>
                }
                <th>
                    @Html.DisplayNameFor(model => model.cv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.paperId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.dt_created)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Job.jobName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Job.applicationFinish)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Reviews.First().interviewDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Reviews.First().review1)
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody id="tableData">

            @foreach (var item in Model)
            {
                <tr>
                    @if ((int)Session["isAdmin"] == 1)
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.User.userId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.printName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.email)
                        </td>
                    }

                    <td>
                        <form target="_blank" action=@Url.Action("Download", "Applications", new { id = item.applicationId })>
                            <button class="btn btn-primary" target="_blank" onclick="location.href='@Url.Action("Download", "Applications", new { id = item.applicationId })'">
                                <span class="glyphicon glyphicon-download-alt"></span> Download
                            </button>
                        </form>


                    </td>
                    <td>
                        @if (item.paperId != null)
                        {
                            <a href=@Url.Action("Edit", "InterviewQuestionPapers", new { id = item.paperId })><i class="glyphicon glyphicon-zoom-in"> Go to Interview </i></a>
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.paperId)
                        }

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.dt_created)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Job.jobName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Job.applicationFinish)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.status)
                    </td>
                    <td>
                        @if (item.Reviews.Count() > 0)
                        {
                            @Html.DisplayFor(modelItem => item.Reviews.First().interviewDate)
                        }
                        else
                        {
                            @Html.Display("TBA")
                        }
                    </td>
                    <td>
                        @if (item.Reviews.Count() > 0)
                        {
                            @Html.DisplayFor(modelItem => item.Reviews.First().review1)
                        }
                        else
                        {
                            @Html.Display("TBA")
                        }

                    </td>
                    <td>
                        @if ((int)Session["isAdmin"] == 1 && item.status.Contains("Pending"))
                        {
                            <a href=@Url.Action("Review", "Applications", new { id = item.applicationId })><i class="glyphicon glyphicon-edit"> Review </i></a>
                        }
                        <a href=@Url.Action("Details", new { id = item.applicationId })><i class="glyphicon glyphicon-zoom-in"> Details </i></a>
                        @if ((int)Session["isAdmin"] == 1 && item.status.Contains("Pending"))
                        {
                            <a href=@Url.Action("Delete", new { id = item.applicationId })><i class="glyphicon glyphicon-remove"> Delete </i></a>
                        }
                        
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

@if ((int)Session["isAdmin"] == 1)
{
    <script>
        var table2_Props = {
            paging: true,
            paging_length: 3,
            rows_counter: true,
            rows_counter_text: "Applications:",
            btn_reset: true,
            loader: true,
            loader_text: "Loading...",
            col_3: "none",
            col_4: "none",
            col_8: "select",
            col_10: "none",
            col_11: "none",
            display_all_text: " [ Show all ] ",
            sort_select: true
        };
        var tf2 = setFilterGrid("myTable", table2_Props);

        var table = document.getElementById("tableData");
        var rows = table.getElementsByTagName("tr");
        for (i = 0; i < rows.length; i++) {
            var td = rows[i].getElementsByTagName("td")[8];
            var context = (td.textContent || td.innerText);

            if (context.includes("Accepted")) {
                td.style.color = "green";
            } else if (context.includes("Pending")) {
                td.style.color = "orange";
            } else if (context.includes("Denied")) {
                td.style.color = "red";
            } else if (context.includes("Interview")) {
                td.style.color = "blue";
            }
        }
    </script>
}
else
{
    <script>
        var table2_Props = {
            paging: true,
            paging_length: 3,
            rows_counter: true,
            rows_counter_text: "Applications:",
            btn_reset: true,
            loader: true,
            loader_text: "Loading...",
            col_0: "none",
            col_1: "none",
            col_5: "select",
            col_8: "none",
            display_all_text: " [ Show all ] ",
            sort_select: true
        };
        var tf2 = setFilterGrid("myTable", table2_Props);

        var table = document.getElementById("tableData");
        var rows = table.getElementsByTagName("tr");
        for (i = 0; i < rows.length; i++) {
            var td = rows[i].getElementsByTagName("td")[5];
            var context = (td.textContent || td.innerText);
            if (context.includes("Accepted")) {
                td.style.color = "green";
            } else if (context.includes("Pending")) {
                td.style.color = "orange";
            } else if (context.includes("Denied")) {
                td.style.color = "red";
            } else if (context.includes("Interview")) {
                td.style.color = "blue";
            }
        }
    </script>
}